version: '3'

services:
  middleware:
    build: ./middleware
    image: alcatraz9/seiveai_middleware
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

    ports:
      - "5002:5002"

    volumes: 
      -  ./middleware:/app/middleware 

    command: ["flask", "run", "--port=5002", '--host=0.0.0.0']

  webapp:
    build: ./webapp

    depends_on: 
      - middleware 
    image: alcatraz9/seiveai_webapp

    environment:
      - NODE_ENV=production

    ports:
      - '5000:5000'

    volumes: 
      - ./webapp/uploads:/app/uploads
      - ./webapp/api:/app/api
      - ./webapp/client:/app/client